export const transactionsData = [
    {
      name: "Subham Kumar",
      rollno: 1904090,
      branch: "Chemical",
      syr: 20000,
      tyr: 20000,
      fyr: 20000,
    },
    {
      name: "Rohan Anand",
      rollno: 1905075,
      branch: "Civil",
      syr: 20000,
      tyr: 20000,
      fyr: 20000,
    },
    {
      name: "Jayesh Kumar",
      rollno: 1909018,
      branch: "Computer Science",
      syr: 20000,
      tyr: 20000,
      fyr: 20000,
    },
    {
      name: "Kumar Shashwat",
      rollno: 1906023,
      branch: "Electronics and Communication",
      syr: 20000,
      tyr: 20000,
      fyr: 20000,
    },
    {
      name: "Suraj Kumar",
      rollno: 1901098,
      branch: "Electrical",
      syr: 20000,
      tyr: 20000,
      fyr: 20000,
    },
    {
      name: "Ankit Kumar",
      rollno: 1911009,
      branch: "Information Technology",
      syr: 20000,
      tyr: 20000,
      fyr: 20000,
    },
    {
      name: "Shubham Kumar Gupta",
      rollno: 1900116,
      branch: "Mechanical",
      syr: 20000,
      tyr: 20000,
      fyr: 20000,
    },
    {
      name: "Amit Kumar Sharma",
      rollno: 1903006,
      branch: "Metallurgy",
      syr: 20000,
      tyr: 20000,
      fyr: 20000,
    },
    {
      name: "Vishal Kumar Pathak",
      rollno: 1906023,
      branch: "Mining",
      syr: "Ineligible",
      tyr: 20000,
      fyr: "Ineligible",
    },
    {
      name: "Mohammad Mehran",
      rollno: 1908050,
      branch: "Electrical",
      syr: 20000,
      tyr: "Ineligible",
      fyr: "Ineligible",
    },
    {
      name: "Deepak Kumar Koda",
      rollno: 1801034,
      branch: "Electrical",
      syr: "Ineligible",
      tyr: 20000,
      fyr: "N/A",
    },
  
    {
      name: "Raghunandan Singh",
      rollno: "2002004D",
      branch: "Production",
      syr: 20000,
      tyr: 20000,
      fyr: 20000,
    },
  
    {
      name: "Ashutosh Kumar Pandey",
      rollno: 2004023,
      branch: "Chemical",
      syr: "N/A",
      tyr: 20000,
      fyr: "TBD",
    },
    {
      name: "Ankur Kumar",
      rollno: 2005027,
      branch: "Civil",
      syr: "N/A",
      tyr: 20000,
      fyr: "TBD",
    },
    {
      name: "Ayush Anshu",
      rollno: 2009001,
      branch: "Computer Science",
      syr: "N/A",
      tyr: 20000,
      fyr: "TBD",
    },
    {
      name: "Harsh Kumar",
      rollno: 2001114,
      branch: "Electrical",
      syr: "N/A",
      tyr: 20000,
      fyr: "TBD",
    },
    {
      name: "Aman Kumar",
      rollno: 2006009,
      branch: "Electronics and Communication",
      syr: "N/A",
      tyr: 20000,
      fyr: "TBD",
    },
    {
      name: "Navneet Sinha",
      rollno: "211007D",
      branch: "Information Technology",
      syr: "N/A",
      tyr: 20000,
      fyr: "TBD",
    },
    {
      name: "Shubham Barnawal",
      rollno: 2000126,
      branch: "Mechanical",
      syr: "N/A",
      tyr: 20000,
      fyr: "TBD",
    },
    {
      name: "Akash Kumar",
      rollno: "2103001D",
      branch: "Metallurgy",
      syr: "N/A",
      tyr: 20000,
      fyr: "TBD",
    },
    {
      name: "Raj Kumar",
      rollno: 2008039,
      branch: "Mining",
      syr: "N/A",
      tyr: 20000,
      fyr: "TBD",
    },
    {
      name: "Shashikant",
      rollno: "2102017D",
      branch: "Production",
      syr: "N/A",
      tyr: 20000,
      fyr: "TBD",
    },
  
    {
      name: "Rajshree",
      rollno: 21030430065,
      branch: "Civil",
      syr: "N/A",
      tyr: 20000,
      fyr: "TBD",
    },
    {
      name: "Abhishek Kumar",
      rollno: 21030455001,
      branch: "Electrical",
      syr: "N/A",
      tyr: 20000,
      fyr: "TBD",
    },
    {
      name: "Aman Kumar",
      rollno: 21030455003,
      branch: "Electrical",
      syr: "N/A",
      tyr: 20000,
      fyr: "TBD",
    },
    {
      name: "Rena Kumari",
      rollno: 21030495012,
      branch: "Mechanical",
      syr: "N/A",
      tyr: 20000,
      fyr: "TBD",
    },
    {
      name: "Ritika Kumari Singh",
      rollno: 21030425008,
      branch: "Chemical",
      syr: "N/A",
      tyr: 20000,
      fyr: "TBD",
    },
    {
      name: "Ashish Kumar Mishra",
      rollno: "221030420028",
      branch: "Chemical",
      syr: "N/A",
      tyr: 20000,
      fyr: "TBD",
    },
    {
      name: "Aayushi Singh",
      rollno: 21030465001,
      branch: "Electronics",
      syr: "N/A",
      tyr: 20000,
      fyr: "TBD",
    },
    {
      name: "Kheya Rani Das",
      rollno: "21030460026",
      branch: "Electronics",
      syr: "N/A",
      tyr: 20000,
      fyr: "TBD",
    },
    {
      name: "Parvati Kumari",
      rollno: 21030505003,
      branch: "Metallurgy",
      syr: "N/A",
      tyr: 20000,
      fyr: "TBD",
    },
    {
      name: "Swapnil Pandit",
      rollno: "21030505003",
      branch: "Information Technology",
      syr: "N/A",
      tyr: 20000,
      fyr: "TBD",
    },
  ];

export  const contributorData = [
  {
    sectionName: "Founding Members",
    members: [
      {
        date: "XX/XX/XXXX",
        name: "ANANT BHATT",
        contributedAmount: 0,
        debitAmount: 0,
        totalAmount: 0,
      },
      {
        date: "XX/XX/XXXX",
        name: "AJIT KUMAR",
        contributedAmount: 0,
        debitAmount: 0,
        totalAmount: 0,
      },
      {
        date: "XX/XX/XXXX",
        name: "ANIL KUMAR",
        contributedAmount: 0,
        debitAmount: 0,
        totalAmount: 0,
      },
      {
        date: "XX/XX/XXXX",
        name: "MADHURESH NAGSHAIN",
        contributedAmount: 0,
        debitAmount: 0,
        totalAmount: 0,
      },
      {
        date: "XX/XX/XXXX",
        name: "MURARI PRASAD",
        contributedAmount: 0,
        debitAmount: 0,
        totalAmount: 0,
      },
      {
        date: "XX/XX/XXXX",
        name: "PANDEY BRIJ BHUSHAN PRASAD",
        contributedAmount: 0,
        debitAmount: 0,
        totalAmount: 0,
      },
      {
        date: "XX/XX/XXXX",
        name: "RAJIV TEWARY",
        contributedAmount: 0,
        debitAmount: 0,
        totalAmount: 0,
      },
      {
        date: "XX/XX/XXXX",
        name: "RAJAT KANTI ROY",
        contributedAmount: 0,
        debitAmount: 0,
        totalAmount: 0,
      },
      {
        date: "XX/XX/XXXX",
        name: "RAJEEVA RANJAN",
        contributedAmount: 0,
        debitAmount: 0,
        totalAmount: 0,
      },
      {
        date: "XX/XX/XXXX",
        name: "RANJIT VARMA",
        contributedAmount: 0,
        debitAmount: 0,
        totalAmount: 0,
      },
      {
        date: "XX/XX/XXXX",
        name: "SUJIT KUMAR MITRA",
        contributedAmount: 0,
        debitAmount: 0,
        totalAmount: 0,
      },
      {
        date: "XX/XX/XXXX",
        name: "VIJAY KUMAR PRADHAN",
        contributedAmount: 0,
        debitAmount: 0,
        totalAmount: 0,
      },
    ],
  },
  {
    sectionName: "Additional Members",
    members: [
      {
        date: "XX/XX/XXXX",
        name: "ABHAY K.VERMA",
        contributedAmount: 0,
        debitAmount: 0,
        totalAmount: 0,
      },
      {
        date: "XX/XX/XXXX",
        name: "BAIJU PRASAD GUPTA",
        contributedAmount: 0,
        debitAmount: 0,
        totalAmount: 0,
      },
      {
        date: "XX/XX/XXXX",
        name: "BIPIN BIHARI VERMA",
        contributedAmount: 0,
        debitAmount: 0,
        totalAmount: 0,
      },
      {
        date: "XX/XX/XXXX",
        name: "BINOD KUMAR JHA",
        contributedAmount: 0,
        debitAmount: 0,
        totalAmount: 0,
      },
      {
        date: "XX/XX/XXXX",
        name: "DEBMALYA GHOSH",
        contributedAmount: 0,
        debitAmount: 0,
        totalAmount: 0,
      },
      {
        date: "XX/XX/XXXX",
        name: "INDRADEO NARAYAN SINHA",
        contributedAmount: 0,
        debitAmount: 0,
        totalAmount: 0,
      },
      {
        date: "XX/XX/XXXX",
        name: "MANOHAR SINGH SAINI",
        contributedAmount: 0,
        debitAmount: 0,
        totalAmount: 0,
      },
      {
        date: "XX/XX/XXXX",
        name: "MUKTESHWAR CH.",
        contributedAmount: 0,
        debitAmount: 0,
        totalAmount: 0,
      },
      {
        date: "XX/XX/XXXX",
        name: "MUKUND CHANDRA BHATTA",
        contributedAmount: 0,
        debitAmount: 0,
        totalAmount: 0,
      },
      {
        date: "XX/XX/XXXX",
        name: "NARENDRA NARAYAN MISHRA",
        contributedAmount: 0,
        debitAmount: 0,
        totalAmount: 0,
      },
      {
        date: "XX/XX/XXXX",
        name: "NIRMAL KUMAR",
        contributedAmount: 0,
        debitAmount: 0,
        totalAmount: 0,
      },
      {
        date: "XX/XX/XXXX",
        name: "PRAKASH BIHARI DAS",
        contributedAmount: 0,
        debitAmount: 0,
        totalAmount: 0,
      },
      {
        date: "XX/XX/XXXX",
        name: "PRABHAT JHA",
        contributedAmount: 0,
        debitAmount: 0,
        totalAmount: 0,
      },
      {
        date: "XX/XX/XXXX",
        name: "PRADIP KUMAR",
        contributedAmount: 0,
        debitAmount: 0,
        totalAmount: 0,
      },
      {
        date: "XX/XX/XXXX",
        name: "RADHE SHYAM MISHRA",
        contributedAmount: 0,
        debitAmount: 0,
        totalAmount: 0,
      },
      {
        date: "XX/XX/XXXX",
        name: "RAM BILAS SINGH",
        contributedAmount: 0,
        debitAmount: 0,
        totalAmount: 0,
      },
      {
        date: "XX/XX/XXXX",
        name: "RAK KRIPAL SINGH",
        contributedAmount: 0,
        debitAmount: 0,
        totalAmount: 0,
      },
      {
        date: "XX/XX/XXXX",
        name: "RANG NATH JHA",
        contributedAmount: 0,
        debitAmount: 0,
        totalAmount: 0,
      },
      {
        date: "XX/XX/XXXX",
        name: "SHAMBHU DAS",
        contributedAmount: 0,
        debitAmount: 0,
        totalAmount: 0,
      },
      {
        date: "XX/XX/XXXX",
        name: "SHYAM NANDAN MISHRA",
        contributedAmount: 0,
        debitAmount: 0,
        totalAmount: 0,
      },
      {
        date: "XX/XX/XXXX",
        name: "SHYAM SUNDER YADAV",
        contributedAmount: 0,
        debitAmount: 0,
        totalAmount: 0,
      },
      {
        date: "XX/XX/XXXX",
        name: "UMASHANKAR YADAV",
        contributedAmount: 0,
        debitAmount: 0,
        totalAmount: 0,
      },
      {
        date: "XX/XX/XXXX",
        name: "YOGENDRA TIWARY",
        contributedAmount: 0,
        debitAmount: 0,
        totalAmount: 0,
      },
    ],
  },
];  